config/routes.rb
Spargris::Application.routes.draw do
  localized(I18n.available_locales) do
    resources :budget_posts

    resources :budgets do
      resources :budget_items
    end

    resources :tags, :except => [:new, :create]

    resources :transactions do
      resources :transaction_items
    end

    resources :vendors

    get 'user', :to => 'users#show', :as => :user
    put 'user', :to => 'users#update', :as => :update_user
    get 'user/edit', :to => 'users#edit', :as => :edit_user
    devise_for :users

    match 'dashboard', :to => 'dashboard#index', :as => :dashboard
  end

  root :to => "frontpage#index"
end

app/models/budget_post.rb
class BudgetPost < ActiveRecord::Base
  attr_accessible :user_id, :name, :description, :parent_id

  belongs_to :user

  has_many :budget_items
  has_many :budgets, :through => :budget_items
  has_many :transaction_items
  has_many :transactions, :through => :transaction_items

  validates_presence_of :name

  default_scope order("name ASC")
end

app/controllers/budget_posts_controller.rb
class BudgetPostsController < ApplicationController
  # GET /budget_posts
  # GET /budget_posts.xml
  def index
    @budget_posts = current_user.budget_posts.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @budget_posts }
    end
  end

  # GET /budget_posts/1
  # GET /budget_posts/1.xml
  def show
    @budget_post = current_user.budget_posts.find(params[:id])
    @transactions = @budget_post.transactions

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @budget_post }
    end
  end

  # GET /budget_posts/new
  # GET /budget_posts/new.xml
  def new
    @budget_post = BudgetPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @budget_post }
    end
  end

  # GET /budget_posts/1/edit
  def edit
    @budget_post = current_user.budget_posts.find(params[:id])
  end

  # POST /budget_posts
  # POST /budget_posts.xml
  def create
    @budget_post = current_user.budget_posts.new(params[:budget_post])

    respond_to do |format|
      if @budget_post.save
        format.html { redirect_to(@budget_post, :notice => t('categories.create.success_notice')) }
        format.xml  { render :xml => @budget_post, :status => :created, :location => @budget_post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @budget_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /budget_posts/1
  # PUT /budget_posts/1.xml
  def update
    @budget_post = BudgetPost.find(params[:id])

    respond_to do |format|
      if @budget_post.update_attributes(params[:budget_post])
        format.html { redirect_to(@budget_post, :notice => t('categories.update.success_notice')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @budget_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /budget_posts/1
  # DELETE /budget_posts/1.xml
  def destroy
    @budget_post = current_user.budget_posts.find(params[:id])
    @budget_post.destroy

    respond_to do |format|
      format.html { redirect_to(budget_posts_url, :notice => t('categories.destroy.success_notice')) }
      format.xml  { head :ok }
    end
  end
end

app/views/budget_posts/_form.html.haml
= semantic_form_for @budget_post do |form|
  = form.inputs do
    = form.input :name
    = form.input :description
  = form.buttons do
    = form.submit

app/views/budget_posts/_list.html.haml
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Count
      %th Amount
  %tbody
  - @budget_posts.each do |budget_post|
    %tr
      %td= link_to budget_post.name, budget_post
      %td= budget_post.description
      %td= budget_post.transactions.count
      - tsum = budget_post.transactions.sum(:amount).to_f
      - klass = tsum >= 0.0 ? "plus" : "minus"
      %td.currency{:class => klass}= number_to_currency tsum
      %td= modification_image_links(budget_post)
  %tfoot
    %tr
      %th Name
      %th Description
      %th Count
      %th Amount

app/views/budget_posts/edit.html.haml
- title edit_title(@budget_post)

%h2
  = edit_title(@budget_post)
  = link_to image_tag("icons/cross.png", :alt => "Back"), @budget_post

= render 'form'

app/views/budget_posts/index.html.haml
- title "Budget post"

= render :partial => "list", :locals => { :budget_posts => @budget_posts }

= paginate @budget_posts

= link_to "New budget post", new_budget_post_path

app/views/budget_posts/new.html.haml
- title new_title(@budget_post)
%h2= new_title(@budget_post)

= render 'form'

= link_to t('common.back'), budget_posts_path

app/views/budget_posts/show.html.haml
- title @budget_post.name

%p= @budget_post.description

= render :partial => 'transactions/list', :locals => { :transactions => @transactions }

= link_to "Edit", edit_budget_post_path(@budget_post), :class => "btn"
= link_to "Delete", @budget_post, :confirm => 'Säker?', :method => :delete, :class => "btn danger"