config/routes.rb
Spargris::Application.routes.draw do
  localized(I18n.available_locales) do
    resources :budget_posts

    resources :budgets do
      resources :budget_items
    end

    resources :tags, :except => [:new, :create]

    resources :transactions do
      resources :transaction_items
    end

    resources :vendors

    get 'user', :to => 'users#show', :as => :user
    put 'user', :to => 'users#update', :as => :update_user
    get 'user/edit', :to => 'users#edit', :as => :edit_user
    devise_for :users

    match 'dashboard', :to => 'dashboard#index', :as => :dashboard
  end

  root :to => "frontpage#index"
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :user
  has_many :budget_items
  has_many :budget_posts, :through => :budget_items

  attr_accessible :starts_at, :ends_at, :budget_items_attributes
  accepts_nested_attributes_for :budget_items, :allow_destroy => true

  validates_presence_of :user, :starts_at, :ends_at

  default_scope order("starts_at DESC")

  scope :current, lambda {
    where('starts_at < ? AND ends_at > ?', Time.zone.now, Time.zone.now)
  }

  scope :chronological_order, order("starts_at ASC")
  scope :reverse_chronological_order, order("starts_at DESC")

  def days
    @days ||= (self.ends_at-self.starts_at)/1.day.to_f
  end

  def days_gone
    return 0 if self.starts_at.future?
    [(Time.zone.now-self.starts_at)/1.day.to_f, days].min
  end

  def days_left
    return days if self.starts_at.future?
    [(self.ends_at-Time.zone.now)/1.day.to_f, 0].max
  end

  def amount
    @amount ||= budget_items.sum(:amount)
  end

  def sum
    @sum ||= budget_items.inject(0) { |result, element| result + element.sum }
  end

  def spent
    @spent ||= budget_items.inject(0) { |result, element| result + element.spent }
  end

  def earned
    @earned ||= budget_items.inject(0) { |result, element| result + element.earned }
  end

  def difference
    @difference ||= budget_items.inject(0) { |result, element| result + element.difference }
  end
  alias :diff :difference

  def margin
    -self.difference
  end

  def spent_per_day
    return 0 if self.starts_at.future?
    self.spent / self.days_gone
  end

  def earned_per_day
    return 0 if self.starts_at.future?
    self.earned / self.days_gone
  end

  def difference_per_day
    return 0 if self.starts_at.future?
    self.diff / self.days_gone
  end
  alias :diff_per_day :difference_per_day

  def margin_per_day
    return 0 if self.ends_at.past?
    self.margin / self.days_left
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  # GET /budgets
  # GET /budgets.xml
  def index
    @budgets = current_user.budgets.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @budgets }
    end
  end

  # GET /budgets/1
  # GET /budgets/1.xml
  def show
    @budget = current_user.budgets.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @budget }
    end
  end

  # GET /budgets/new
  # GET /budgets/new.xml
  def new
    if params[:template]
      @budget = current_user.budgets.find(params[:template])
      @budget.id = nil
    else
      @budget = current_user.budgets.new
      @budget.starts_at = Time.zone.now.to_datetime.beginning_of_month.beginning_of_day
      @budget.ends_at = Time.zone.now.to_datetime.end_of_month.end_of_day
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @budget }
    end
  end

  # GET /budgets/1/edit
  def edit
    @budget = current_user.budgets.find(params[:id])
  end

  # POST /budgets
  # POST /budgets.xml
  def create
    @budget = current_user.budgets.new(params[:budget])

    respond_to do |format|
      if @budget.save
        format.html { redirect_to(@budget, :notice => t('budgets.create.success_notice')) }
        format.xml  { render :xml => @budget, :status => :created, :location => @budget }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @budget.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /budgets/1
  # PUT /budgets/1.xml
  def update
    @budget = current_user.budgets.find(params[:id])

    respond_to do |format|
      if @budget.update_attributes(params[:budget])
        format.html { redirect_to(@budget, :notice => t('budgets.update.success_notice')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @budget.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.xml
  def destroy
    @budget = current_user.budgets.find(params[:id])
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to(budgets_url, :notice => t('budgets.destroy.success_notice')) }
      format.xml  { head :ok }
    end
  end
end

app/views/budgets/_budget_item_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :budget_post, {:include_blank => false}
    = f.input :amount
    %li
      %label
      = link_to_remove_association "Remove budget item", f, :class => "btn small"

app/views/budgets/_form.html.haml
= semantic_form_for @budget do |form|
  = form.inputs :name => "Tid" do
    = form.input :starts_at, :as => :string
    = form.input :ends_at, :as => :string

  = form.inputs :name => BudgetItem.model_name.human do
    = form.semantic_fields_for :budget_items do |item|
      = render 'budget_item_fields', :f => item
    .links
      = link_to_add_association 'add budget item', form, :budget_items, :class => "btn small success"
  = form.buttons do
    = form.submit :class => "btn primary"

app/views/budgets/_list.html.haml
%table
  %thead
    %tr
      %th Start
      %th End
      %th Diff
      %th Spending margin
  %tbody
    - budgets.each do |budget|
      %tr
        %td= budget.starts_at.to_s(:short)
        %td= budget.ends_at.to_s(:short)
        - klass = budget.diff >= 0 ? "plus" : "minus"
        %td.currency{:class => klass}
          = number_to_currency budget.diff
        - klass = budget.diff >= 0 ? "plus" : "minus"
        %td.currency{:class => klass}
          = number_to_currency(-budget.margin_per_day) + '/d'
        %td= modification_image_links(budget)
  %tfoot
    %tr
      %th Start
      %th End
      %th Diff
      %th Spending margin

app/views/budgets/edit.html.haml
- title "Budget"

= render 'form'

- content_for(:side) do
  %h2 Actions
  %ul.none
    %li= link_to t('common.back'), @budget, :class => "btn"

app/views/budgets/index.html.haml
- title "Budget"

= render "list", { :budgets => @budgets }

= paginate @budgets

= link_to "New budget", new_budget_path, :class => "btn primary"

- content_for(:side) do
  %p
    Budgets are a central part of this application.
    Budgets allow you to plan your economy ahead of time,
    as well as to keep track of progress.

app/views/budgets/new.html.haml
- title "Budget"

= render 'form'

- content_for(:side) do
  %h2 Actions
  %ul
    %li= link_to t('common.back'), budgets_path, :class => "btn"

app/views/budgets/show.html.haml
- title "Budget ##{@budget.id}"

%p
  %dl
    %dt Start
    %dd= @budget.starts_at
    %dt End
    %dd= @budget.ends_at

%p
  %table
    %thead
      %tr
        %th Budget post
        %th Budgeted amount
        %th Bookkept amount
        %th Diff
    %tbody
      - @budget.budget_items.each do |budget_item|
        %tr
          %td= link_to budget_item.budget_post.name, budget_item.budget_post
          - klass = budget_item.amount >= 0 ? "plus" : "minus"
          %td.currency{:class => klass}= number_to_currency budget_item.amount
          - klass = budget_item.sum >= 0 ? "plus" : "minus"
          %td.currency{:class => klass}= number_to_currency budget_item.sum
          - klass = budget_item.diff >= 0 ? "plus" : "minus"
          %td.currency{:class => klass}= number_to_currency budget_item.diff
    %tfoot
      %tr
        %td Totalt
        - klass = @budget.amount >= 0 ? "plus" : "minus"
        %td.currency{:class => klass}= number_to_currency @budget.amount
        - klass = @budget.sum >= 0 ? "plus" : "minus"
        %td.currency{:class => klass}= number_to_currency @budget.sum
        - klass = @budget.diff >= 0 ? "plus" : "minus"
        %td.currency{:class => klass}= number_to_currency @budget.diff
      %tr
        %th Budget post
        %th Budgeted amount
        %th Bookkept amount
        %th Diff

= link_to "Edit budget", edit_budget_path(@budget), :class => "btn"
= link_to "Delete budget", @budget, :confirm => 'Säker?', :method => :delete, :class => "btn danger"

- content_for(:side) do
  %p
    This page gives you a more detailed description of the given budget.
    You can see what amount has been set for a given budget post,
    how much of it has been spent and the difference.