config/routes.rb
Spargris::Application.routes.draw do
  localized(I18n.available_locales) do
    resources :budget_posts

    resources :budgets do
      resources :budget_items
    end

    resources :tags, :except => [:new, :create]

    resources :transactions do
      resources :transaction_items
    end

    resources :vendors

    get 'user', :to => 'users#show', :as => :user
    put 'user', :to => 'users#update', :as => :update_user
    get 'user/edit', :to => 'users#edit', :as => :edit_user
    devise_for :users

    match 'dashboard', :to => 'dashboard#index', :as => :dashboard
  end

  root :to => "frontpage#index"
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  belongs_to :user

  has_many :transactions

  validates_presence_of :name

  default_scope order("name ASC")
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  # GET /vendors
  # GET /vendors.xml
  def index
    @vendors = current_user.vendors.where("name like ?", "%#{params[:term]}%").page(params[:page]).per(params[:per])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @vendors }
      format.json { render :json => @vendors.map(&:attributes).each{|t| t[:value] = t['name'] } }
    end
  end

  # GET /vendors/1
  # GET /vendors/1.xml
  def show
    @vendor = current_user.vendors.find(params[:id])
    @transactions = @vendor.transactions.page(params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vendor }
    end
  end

  # GET /vendors/new
  # GET /vendors/new.xml
  def new
    @vendor = Vendor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vendor }
    end
  end

  # GET /vendors/1/edit
  def edit
    @vendor = current_user.vendors.find(params[:id])
  end

  # POST /vendors
  # POST /vendors.xml
  def create
    @vendor = current_user.vendors.new(params[:vendor])

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to(@vendor, :notice => 'Vendor was successfully created.') }
        format.xml  { render :xml => @vendor, :status => :created, :location => @vendor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vendor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vendors/1
  # PUT /vendors/1.xml
  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
        format.html { redirect_to(@vendor, :notice => 'Vendor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vendor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.xml
  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to(vendors_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/vendors/_form.html.haml
= semantic_form_for @vendor do |form|
  = form.input :name
  = form.submit

app/views/vendors/_list.html.haml
%table
  %thead
    %tr
      %th Name
  %tbody
    - @vendors.each do |vendor|
      %tr
        %td= vendor.name
        %td= modification_image_links(vendor)

app/views/vendors/edit.html.haml
- title edit_title(@vendor)
%h2
  = edit_title(@vendor)
  = link_to image_tag("icons/cross.png", :alt => "Back"), @vendor

= render 'form'

app/views/vendors/index.html.haml
- title index_title(Vendor)

%h2
  = index_title(Vendor)
  = link_to image_tag("icons/add.png", :alt => "New vendor"), new_vendor_path

= render "list", :locals => { :vendors => @vendors }

= paginate @vendors

app/views/vendors/new.html.haml
- title new_title(@vendor)
%h2= new_title(@vendor)

= render 'form'

= link_to t('common.back'), vendors_path

app/views/vendors/show.html.haml
- title show_title(@vendor)
%h2
  = show_title(@vendor)
  = link_to image_tag("icons/wrench.png", :alt => "Edit"), edit_vendor_path(@vendor)
  = link_to image_tag("icons/delete.png", :alt => "Delete"), @vendor, :confirm => 'Säker?', :method => :delete

= render :partial => "transactions/list", :locals => { :transactions => @transactions }

= paginate @transactions