config/routes.rb
Spargris::Application.routes.draw do
  localized(I18n.available_locales) do
    resources :budget_posts

    resources :budgets do
      resources :budget_items
    end

    resources :tags, :except => [:new, :create]

    resources :transactions do
      resources :transaction_items
    end

    resources :vendors

    get 'user', :to => 'users#show', :as => :user
    put 'user', :to => 'users#update', :as => :update_user
    get 'user/edit', :to => 'users#edit', :as => :edit_user
    devise_for :users

    match 'dashboard', :to => 'dashboard#index', :as => :dashboard
  end

  root :to => "frontpage#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.xml
  def index
    @transactions = current_user.transactions.page(params[:page]).per(params[:per])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = current_user.transactions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    if params[:template]
      @transaction = current_user.transactions.find(params[:template])
      @transaction.id = nil
    else
      @transaction = Transaction.new
    end

    @transaction.timestamp = Time.zone.now unless @transaction.timestamp
    @transaction.transaction_items.build if @transaction.transaction_items.blank?

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = current_user.transactions.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.xml
  def create
    @transaction = current_user.transactions.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully created.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/transactions/_form.html.haml
= semantic_form_for(@transaction, html: { class: "form-horizontal" }) do |form|
  = form.semantic_errors
  = form.semantic_errors :base

  = form.input :timestamp, as: :string
  = form.input :vendor_name, as: :string
  = form.input :tag_list
  = form.input :description

  = form.inputs :name => "Transaktionsdelar" do
    = form.semantic_fields_for :transaction_items do |item|
      = render 'transaction_item_fields', :f => item
    .links
      = link_to_add_association 'Lägg till transaktionsdel', form, :transaction_items

  = form.buttons do
    = form.commit_button button_html: { class: "btn-primary" }

app/views/transactions/_list.html.haml
%table
  %thead
    %th Tidsstämpel
    %th Belopp
    %th Affär
    %th Beskrivning
  %tbody
    - transactions.each do |transaction|
      %tr
        %td= transaction.timestamp.to_s(:iso8601)
        - klass = transaction.amount >= 0.0 ? "plus" : "minus"
        %td.currency{:class => klass}= number_to_currency(transaction.amount)
        %td= link_to(transaction.vendor.name, transaction.vendor) if transaction.vendor
        %td= truncate transaction.description if transaction.description
        %td= modification_image_links(transaction)
  %tfoot
    %tr
      %td
      - sum = transactions.map(&:amount).sum
      - klass = sum >= 0.0 ? "plus" : "minus"
      %td.currency{:class => klass}= number_to_currency(sum)
      %td Totalt
      %td
      %td
    %tr
      %th Tidsstämpel
      %th Belopp
      %th Affär
      %th Beskrivning

app/views/transactions/_transaction_item_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :budget_post, {:include_blank => false}
    = f.input :description
    = f.input :amount
    %li
      %label
      = link_to_remove_association "Remove item", f, :class => "btn danger"

app/views/transactions/edit.html.haml
- title edit_title(@transaction)

%h2
  = edit_title(@transaction)
  = link_to image_tag("icons/cross.png", :alt => "Back"), @transaction

= render 'form'

app/views/transactions/index.html.haml
- title "Transaktion"

%h2
  Listar transaktioner
  = link_to image_tag("icons/add.png", :alt => "New transaction"), new_transaction_path

= render :partial => "list", :locals => { :transactions => @transactions }

= paginate @transactions

app/views/transactions/new.html.haml
%h2 New transaction

= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
- title "Transaktion"

%h2= @transaction.vendor ? link_to(@transaction.vendor.name, @transaction.vendor) : '(ej angivet)'

%h3
  = @transaction.timestamp.to_s(:iso8601)
  = link_to image_tag("icons/wrench.png", :alt => "Edit"), edit_transaction_path(@transaction)
  = link_to image_tag("icons/delete.png", :alt => "Delete"), @transaction, :confirm => 'Säker?', :method => :delete

%p
  %table
    %thead
      %tr
        %th Budget post
        %th Description
        %th Amount
    %tbody
      - @transaction.transaction_items.each do |item|
        %tr
          %td= link_to item.budget_post.name, item.budget_post
          %td= item.description
          - klass = item.amount >= 0 ? "plus" : "minus"
          %td.currency{:class => klass}
            = number_to_currency item.amount
    %tfoot
      %tr
        %th Budget post
        %th Amount


%p
  Beskrivning:
  = @transaction.description || '(ingen)'
%p
  Taggar:
  =raw @transaction.tags.collect{|t| link_to t.name, tag_path(t) }.join(', ')